# Generated by Django 4.2.7 on 2023-11-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='winery',
            name='addresse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='winery',
            name='creation_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
