# Generated by Django 4.2.7 on 2023-11-28 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('winery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('winery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winery.winery')),
            ],
        ),
    ]
