# Generated by Django 4.2.7 on 2023-11-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='type',
            field=models.CharField(choices=[('Blanc', 'Blanc'), ('Rouge', 'Rouge'), ('Rosé', 'Rosé'), ('Pétillant', 'Pétillant')], default='Blanc', max_length=20),
        ),
    ]
