# Generated by Django 4.2.7 on 2023-11-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0002_wine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='alcool_degree',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='creation_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='volume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
