# Generated by Django 4.2.7 on 2023-11-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0003_wine_alcool_degree_wine_creation_year_wine_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='alcool_degree',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='wine',
            name='creation_year',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='wine',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='wine',
            name='volume',
            field=models.CharField(max_length=50),
        ),
    ]
