# Generated by Django 4.2.7 on 2023-11-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0004_alter_wine_alcool_degree_alter_wine_creation_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='weekly_wine',
            field=models.BooleanField(default=False),
        ),
    ]
