# Generated by Django 4.2.7 on 2023-12-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0005_wine_weekly_wine'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='image',
            field=models.ImageField(default=11, upload_to=''),
            preserve_default=False,
        ),
    ]
