# Generated by Django 4.2 on 2024-03-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0006_wine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='type',
            field=models.CharField(choices=[('Blanc', 'Blanc'), ('Rouge', 'Rouge'), ('Rosé', 'Rosé')], default='Blanc', max_length=20),
        ),
    ]
