# Generated by Django 4.2 on 2024-03-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0007_alter_wine_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='price',
            new_name='prix',
        ),
        migrations.AddField(
            model_name='wine',
            name='accompagnement',
            field=models.CharField(default=111, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='niveau',
            field=models.CharField(default=111, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='plat',
            field=models.CharField(default=111, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='repas',
            field=models.CharField(default=1111, max_length=50),
            preserve_default=False,
        ),
    ]
